#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Controlling Bias in Artificial Intelligence

# Short bio or description (displayed in the header)
description: The use of demographically misrepresentative datasets or inappropriate models often leads to social biases in the results of automated models. Context-aware design and implementation of machine learning and artificial intelligence models is, therefore, becoming increasingly necessary. Our group aims to address social biases in AI, with a focus on providing feasible alternatives to currently-used biased models.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/blank.png


faculty:
  - name: Elisa Celis,
    website: https://datascienceethics.org

  - name: Nisheeth Vishnoi
    website: https://www.cs.yale.edu/homes/vishnoi

postdoc:
  - name: Lingxiao Huang
    website: https://scholar.google.com/citations?user=SWz0BvoAAAAJ&hl=en

phd:
  - name: Vijay Keswani,
    website: https://vijaykeswani.github.io/

  - name: Anay Mehrotra
    website: https://anaymehrotra.github.io/

undergrad:
  - name: Chris Hays,
    website: \#

  - name: Yi Chern Tan
    website: \#

alumni: Nishtha Madan, Sayash Kapoor, Farnood Salehi, Damian Straszak, Julia Wei 



###### Demo information

demos:
    - title: Polarization 
      description: Prototype of a balanced content delivery engine
      website: https://fair-personalized-news.herokuapp.com/fast/diversity.php
      image: images/polarization.png

    - title: Online Advertisements 
      description: Simple platform to serve fair advertisements
      website: https://fair-online-advertising.herokuapp.com
      image: images/onlineAd.png

    - title: Multiwinner Voting 
      description: Framework to demonstrate fair multiwinner voting algorithms
      website: https://fair-voting-demo.herokuapp.com
      image: images/voting.png

    - title: Sampling 
      description: Prototype to return gender-balanced image search results
      website: https://fair-image-search.herokuapp.com/imageDiversity.php
      image: images/sampling.png

    - title: Ranking 
      description: Balanced ranking framework with applications to search engines, news feeds and recommendation systems
      website: http://balanced-ranking.herokuapp.com
      image: images/ranking.png

    - title: Classification 
      description: A meta-classification algorithm to return fair and accurate prediction, with respect to various fairness metrics
      website: https://github.com/Trusted-AI/AIF360/blob/master/examples/demo_meta_classifier.ipynb
      image: images/classification.png

    - title: Rebalancing Data 
      description: Python notebook to construct and evaluate unbiased maximum-entropy distributions from biased datasets
      website: https://github.com/vijaykeswani/Fair-Max-Entropy-Distributions/blob/master/FairMaxEnt-expts-1.ipynb
      image: images/rebalancing.png



#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin: 
  pinterest:
  rss:
  twitter:
  stackoverflow: 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: UA-43339302-11

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
#url: http://www.amitmerchant.com/reverie
#enforce_ssl: https://www.amitmerchant.com/reverie

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

